//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiVideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Generos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Generos()
        {
            this.DescripcionArticulo = new HashSet<DescripcionArticulo>();
        }
    
        public int idGenero { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual C_Estado C_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescripcionArticulo> DescripcionArticulo { get; set; }
    }
}
