//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiVideoClub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoClubEntities : DbContext
    {
        public VideoClubEntities()
            : base("name=VideoClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Elenco> C_Elenco { get; set; }
        public virtual DbSet<C_Estado> C_Estado { get; set; }
        public virtual DbSet<C_Generos> C_Generos { get; set; }
        public virtual DbSet<C_Idiomas> C_Idiomas { get; set; }
        public virtual DbSet<C_TandaLaboral> C_TandaLaboral { get; set; }
        public virtual DbSet<C_TipoArticulo> C_TipoArticulo { get; set; }
        public virtual DbSet<C_TipoPersona> C_TipoPersona { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<DescripcionArticulo> DescripcionArticulo { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<RentaDevolucion> RentaDevolucion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
