//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiVideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.RentaDevolucion = new HashSet<RentaDevolucion>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public Nullable<int> idTandaLaboral { get; set; }
        public Nullable<decimal> Porciento { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
    
        public virtual C_Estado C_Estado { get; set; }
        public virtual C_TandaLaboral C_TandaLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentaDevolucion> RentaDevolucion { get; set; }
    }
}
