//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiVideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaDevolucion
    {
        public int NoRenta { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<System.DateTime> FechaRenta { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<int> CantidadDeDias { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual C_Estado C_Estado { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual DescripcionArticulo DescripcionArticulo { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
